### ISSUE TITLE
Shared Memory behaviour

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/rgbd#15]
If a client is created before a server, THAT client will reconnect to any server, if servers are closed and opened again. Any client that connects to an existing server, will not reconnect to another server, if the original server is closed.

**Comment by LarsJanssenTUe** [comment]
Add debugs!

**Comment by MatthijsBurgh** [comment]
> Add debugs!

Doesn't solve the problem. Detecting the connection is closed, is not straight forward.
