### ISSUE TITLE
Robust lifecycle of Sever/Client

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/rgbd#24]
## Issues
1. Server can't create new SHM, so server doesn't boot
2. Clients don't switch between SHM and topic mode.
    - If in topic mode, don't switch to SHM if it comes online
    - If in SHM, doesn't switch to topic mode if SHM isn't written anymore.
3. Server doesn't reconnect to ROS. (ROScore is rebooted)

## Constraints
`2` Needs to be solved before `1` as clients don't close the SHM at the moment. So the server can't create a new SHM. Because the old SHM is still open.
`3` can be solved seperatly.

## Proposed solutions
1. Will be solved if clients close their SHM in case the old server dies.
2. Servers will publish their hostname on a string topic with a frequency X. Clients will use SHM as long as hostname is published on the topic less than Y seconds ago. Otherwise client will switch to topic mode. Client will switch back in case the hostname is published again.
Client will check for the hostname on a fixed rate, not on the `nextImage` call. So the SHM is closed quickly after the server is died and not on a `nextImage` call, which is not called with any fixed rate.
- [X] `Server` publishes hostname on string topic, in case `ServerSHM` is initialized. fb5b7b6cb64f34a0ea52b2723ed2f6ab93259e11, bb3a25c0d47e7fd7d9c31ac87ac199df3897f683 and b680941a73ed2e6ea2897b47a70b470b2abee406
- [ ] ~`ServerSHM` opens SHM on initialization, but can only fill the header on first image~
- [ ] ~`ClientSHM` connects to an SHM with empty header~
- [x] `Client` listens to hostname topic on a fixed (Wall)Rate and switches to and from SHM
3. Check on a fixed rate if master is still ok,
```cpp
if (!ros::master::check())
{
    // Make sure node will die
}
```
Make sure the node will restart in the service/launch file
- [X] Check master on a fixed rate, implemented in e2e000c61bea0b27a6741a1dd7eeb5f580bc0670
- [x] Make sure nodes restart in service/launch files

## Tests
- [x] Standalone testing
- [x] Reconnecting to ROS
- [x] Client switching from SHM to topic mode
- [x] Client switching from topic mode to SHM
- [x] Robust reboot of Server, which requires that old SHM is closed before new server start.

Will fix #15

**Comment by MatthijsBurgh** [comment]
I have checked the performance of `ros::master::check()`. When only running a master and the test node my computer was able to handle around 3000 Hz. When also running `hero-start`, it dropped to around 1200-1300 Hz. 
This is the max number of calls the master can handle, so the maximum number of calls need to be split between all nodes. Performance could drop, in case the master is running on a computer. I am not able to test this at the moment. #corona

The goal of this test was to determine if `ros::master::check()` could be added to the while loops, which runs at max 30 Hz in most nodes. I think this is possible.

**Comment by jlunenburg** [comment]
Sounds like a plan. Obviously needs decent testing ;-). Maybe add a figure to illustrate what happens.

**Comment by MatthijsBurgh** [comment]
I tested on HERO today. There was some lag happening at some points. I think it might be related to the master checks. Still figuring things out

**Comment by MatthijsBurgh** [comment]
I have changed the master check to 1 Hz on the reconnect branch, see b0b5aeb28babbf44464d13df69ac6f3c7f07cf69

**Comment by MatthijsBurgh** [comment]
Wth the master check at max 1 Hz, there is no lag anymore on HERO.
